package com.jackalcode.ecommerceapi.exceptions;

public enum ErrorCode {
    CUSTOMER_NOT_FOUND,
    CUSTOMER_ALREADY_EXISTS,
    CUSTOMER_NOT_AUTHORIZED,
    CATEGORY_ALREADY_EXISTS,
    CATEGORY_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    PRODUCT_ALREADY_EXISTS,
    CART_NOT_FOUND,
    PRODUCT_NOT_IN_CART,
    CART_EMPTY,
    ORDER_NOT_FOUND,
    CHECKOUT_UNSUCCESSFUL,
    EXCEPTION
}
