spring:
    application:
        name: Ecommerce-API
    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
        username: springstudent
        password: springstudent
    jpa:
        show-sql: true
    jwt:
      secret: UpWZaX4+FRlVrCwRZhUrGOWD3ryZmwhhxcqK2iecy78=
management:
  endpoints:
    web:
      exposure:
          include: health,info,metrics
  endpoint:
    health:
        show-components: never
        probes:
          enabled: true